# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.0415},
    {id: 1, size: 0.0415},
    {id: 2, size: 0.0415},
    {id: 3, size: 0.0415},
    {id: 4, size: 0.0415},
    {id: 5, size: 0.0415},
    {id: 6, size: 0.0415},
    {id: 7, size: 0.0415},
    {id: 8, size: 0.0415},
    {id: 9, size: 0.0415},
    {id: 10, size: 0.0415},
    {id: 11, size: 0.0415},
    {id: 12, size: 0.0415},
    {id: 13, size: 0.0415},
    {id: 14, size: 0.0415},
    {id: 15, size: 0.0415},
    {id: 16, size: 0.0415},
    {id: 17, size: 0.0415},
    {id: 18, size: 0.0415},
    {id: 19, size: 0.0415},
    {id: 20, size: 0.0415},
    {id: 21, size: 0.0415},
    {id: 22, size: 0.0415},
    {id: 23, size: 0.0415},
    {id: 24, size: 0.0415},
    {id: 25, size: 0.0415},
    {id: 26, size: 0.0415},
    {id: 27, size: 0.0415},
    {id: 28, size: 0.0415},
    {id: 29, size: 0.0415},
    {id: 30, size: 0.0415},
    {id: 31, size: 0.0415},
    {id: 32, size: 0.0415},
    {id: 33, size: 0.0415},
    {id: 34, size: 0.0415},
    {id: 35, size: 0.0415},
    {id: 36, size: 0.0415},
    {id: 37, size: 0.0415},
    {id: 38, size: 0.0415},
    {id: 39, size: 0.0415},
    {id: 40, size: 0.0415},
    {id: 41, size: 0.0415},
    {id: 42, size: 0.0415},
    {id: 43, size: 0.0415},
    {id: 44, size: 0.0415},
    {id: 45, size: 0.0415},
    {id: 46, size: 0.0415},
    {id: 47, size: 0.0415},
    {id: 48, size: 0.0415},
    {id: 49, size: 0.0415},
    {id: 50, size: 0.0415},
    {id: 51, size: 0.0415},
    {id: 52, size: 0.0415},
    {id: 53, size: 0.0415},
    {id: 54, size: 0.0415},
    {id: 55, size: 0.0415},
    {id: 56, size: 0.0415},
    {id: 57, size: 0.0415},
    {id: 58, size: 0.0415},
    {id: 59, size: 0.0415},
    {id: 60, size: 0.0415},
    {id: 61, size: 0.0415},
    {id: 62, size: 0.0415},
    {id: 63, size: 0.0415},
    {id: 64, size: 0.0415},
    {id: 65, size: 0.0415},
    {id: 66, size: 0.0415},
    {id: 67, size: 0.0415},
    {id: 68, size: 0.0415},
    {id: 69, size: 0.0415},
    {id: 70, size: 0.0415},
    {id: 71, size: 0.0415},
    {id: 72, size: 0.0415},
    {id: 73, size: 0.0415},
    {id: 74, size: 0.0415},
    {id: 75, size: 0.0415},
    {id: 76, size: 0.0415},
    {id: 77, size: 0.0415},
    {id: 78, size: 0.0415},
    {id: 79, size: 0.0415},
    {id: 80, size: 0.0415},
    {id: 81, size: 0.0415},
    {id: 82, size: 0.0415},
    {id: 83, size: 0.0415},
    {id: 84, size: 0.0415},
    {id: 85, size: 0.0415},
    {id: 86, size: 0.0415},
    {id: 87, size: 0.0415},
    {id: 88, size: 0.0415},
    {id: 89, size: 0.0415},
    {id: 90, size: 0.0415},
    {id: 91, size: 0.0415},
    {id: 92, size: 0.0415},
    {id: 93, size: 0.0415},
    {id: 94, size: 0.0415},
    {id: 95, size: 0.0415},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
